//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDB_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfo
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string name_ { get; set; }
        public string address { get; set; }
        public Nullable<int> telnum { get; set; }
        public int docId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual User User { get; set; }
    }
}
